spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        max.in.flight.requests.per.connection: 5
        retry.backoff.ms: 1000


    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP}
      auto-offset-reset: latest
      isolation-level: READ_COMMITTED
      properties:
        spring.json.trusted.packages: by.javaguru.jdmik7.core.*

kafka:
  producer:
    topics:
      promotion: ${KAFKA_INTERNAL_PROMOTIONS_RESPONSES}
      onboarding: ${KAFKA_INTERNAL_ONBOARDING_RESPONSES}
      relocation: ${KAFKA_INTERNAL_RELOCATION_RESPONSES}
      recruitment: ${KAFKA_INTERNAL_RECRUITMENT_RESPONSES}
      resignation: ${KAFKA_INTERNAL_RESIGNATION_RESPONSES}
      education: ${KAFKA_INTERNAL_EDUCATION_RESPONSES}
      businesstrip: ${KAFKA_INTERNAL_BUSINESS_RESPONSES}
      vacation: ${KAFKA_INTERNAL_VACATION_RESPONSES}
      
  consumer:
    topics:
      accounting-allocate-requests: ${KAFKA_ACCOUNTING_ALLOCATE_REQUESTS}

  topic-config:
    partitions: 3
    replicas: 3
    min-in-sync-replicas: 2
