
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        max.in.flight.requests.per.connection: 5
        retry.backoff.ms: 1000


    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP}
      auto-offset-reset: latest
      isolation-level: READ_COMMITTED
      properties:
        spring.json.trusted.packages: by.javaguru.jdmik7.core.*


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

kafka:
  topics:
    accounting-allocate-requests: ${KAFKA_TOPIC_ACCOUNTING_ALLOCATE_REQUESTS}
    resources-check-requests: ${KAFKA_TOPIC_RESOURCES_CHECK_REQUESTS}
    notification-send-requests: ${KAFKA_TOPIC_NOTIFICATION_SEND_REQUESTS}
    internal-business-trip-responses: ${KAFKA_TOPIC_INTERNAL_BUSINESS_TRIP_RESPONSES}
    profiler-update-requests: ${KAFKA_TOPIC_PROFILER_UPDATE_REQUEST}
    business-trip-saga: ${KAFKA_TOPIC_BUSINESS_TRIP_SAGA}
  topic-config:
    partitions: 3
    replicas: 3
    min-in-sync-replicas: 2


resilience4j:
  circuitbreaker:
    instances:
      profiler-service:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        event-consumer-buffer-size: 100
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 4
        ignore-exceptions:              
          - by.javaguru.jdmik7.businesstripservice.exception.ProfilerServiceClientException
    circuit-breaker-aspect-order: 1
  retry:
    retry-aspect-order: 2
    instances:
      profiler-service:
        max-attempts: 3
        wait-duration: 5000
        ignore-exceptions:              
          - by.javaguru.jdmik7.businesstripservice.exception.ProfilerServiceClientException
