spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      isolation-level: READ_COMMITTED
      group-id: ${KAFKA_CONSUMER_GROUP}
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: by.javaguru.jdmik7.core.*
    
kafka:
  consumer:
    topics:
      notification-send-requests: ${KAFKA_NOTIFICATION_SEND_REQUESTS}
